---
title: "STAT_37810_HW2"
author: "Boxin"
date: "10/18/2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

Some preparation work before test

```{r}
source("E:/Likelihood.R")
source("E:/slopevalues.R")
source("E:/prior.R")
source("E:/posterior.R")
source("E:/proposalfunction.R")
source("E:/run_metropolis_MCMC.R")
source("E:/MHsummary.R")

trueA <- 5  
trueB <- 0  
trueSd <- 10  
sampleSize <- 31  

# create independent x-values 
x <- (-(sampleSize-1)/2):((sampleSize-1)/2)
# create dependent values according to ax + b + N(0,sd)
y <-  trueA * x + trueB + rnorm(n=sampleSize,mean=0,sd=trueSd) 
```

Let's now compare different iteration times, we first print out the results in each loop

```{r}
# comparison between different iteration numbers
compare_outcomes <- function(iteration.numbers){
  num.of.iteration <- length(iteration.numbers)  # record the number of different iteration times
  loop.num <- 10
  
  record.compare.mean <- array(dim=c(loop.num, num.of.iteration))
  record.compare.std <- array(dim=c(loop.num, num.of.iteration))
  
  for (i in c(1:loop.num)){
    startvalue <- c(1:3)
    startvalue[1] <- runif(n=1, min=0, max=10)
    startvalue[2] <- rnorm(n=1, sd = 5)
    startvalue[3] <- runif(n=1, min=0, max=30)
    
    print(paste("This is the", i, "loop"))
    
    for (j in c(1:num.of.iteration)){
      chain = run_metropolis_MCMC(startvalue, iteration.numbers[j])
      a.mean <- mean(chain[, 1])
      record.compare.mean[i, j] <- a.mean
      a.std <- sd(chain[, 1])
      record.compare.std[i, j] <- a.std
      print(paste("For iteration times as:", iteration.numbers[j], "the mean is:", a.mean, 
                  "The std is:", a.std))
    }
  }
  
  record.compare <- array(dim=c(loop.num, num.of.iteration))
  
  for (i in c(1:loop.num)){
    for (j in c(1:num.of.iteration)){
      record.compare[i, j] = paste("mean:", round(record.compare.mean[i, j], 3), 
                                   "std:", round(record.compare.std[i, j], 3))
    }
  }
  
  record.compare <- data.frame(record.compare)
  
  for (j in c(1:num.of.iteration)){
    colnames(record.compare)[j] <-  paste("iteration:", iteration.numbers[j])
  }
  
  for (j in c(1:num.of.iteration)){
    colnames(record.compare)[j] <-  paste("iteration:", iteration.numbers[j])
  }
  
  for (i in c(1:loop.num)){
    rownames(record.compare)[i] <- paste("loop ", i)
  }
  
  return(record.compare)
}

iteration.numbers <- c(1000, 10000, 100000)
m.compare.out <- compare_outcomes(iteration.numbers)
```

Now Let's see the result in the table

```{r}
m.compare.out
```

